project:
  type: website
  title: "VA-RP"

format:
  pdf:
    documentclass: article
    include-in-header:
      text: |
        \usepackage{amsmath}
        \DeclareMathOperator*{\argmax}{arg\,max}
